# Generated by Django 5.0.4 on 2024-04-20 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("Giornaliera", "Giornaliera"),
                            ("Settimanale", "Settimanale"),
                            ("Mensile", "Mensile"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "days_of_week",
                    models.CharField(
                        choices=[
                            ("Lun", "Lunedì"),
                            ("Mar", "Martedì"),
                            ("Mer", "Mercoledì"),
                            ("Gio", "Giovedì"),
                            ("Ven", "Venerdì"),
                            ("Sab", "Sabato"),
                            ("Dom", "Domenica"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "time_of_day",
                    models.CharField(
                        choices=[
                            ("06:00", "06:00"),
                            ("07:00", "07:00"),
                            ("08:00", "08:00"),
                            ("09:00", "09:00"),
                            ("10:00", "10:00"),
                            ("11:00", "11:00"),
                            ("12:00", "12:00"),
                            ("13:00", "13:00"),
                            ("14:00", "14:00"),
                            ("15:00", "15:00"),
                            ("16:00", "16:00"),
                            ("17:00", "17:00"),
                            ("18:00", "18:00"),
                            ("19:00", "19:00"),
                            ("20:00", "20:00"),
                            ("21:00", "21:00"),
                            ("22:00", "22:00"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="tracker.activity",
                    ),
                ),
            ],
        ),
    ]
