# Generated by Django 5.0.4 on 2024-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayOfWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("display_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="activity",
            name="days_of_week",
        ),
        migrations.AlterField(
            model_name="activity",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="time_of_day",
            field=models.CharField(
                choices=[
                    ("06:00", "06:00"),
                    ("07:00", "07:00"),
                    ("08:00", "08:00"),
                    ("09:00", "09:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("12:00", "12:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                    ("18:00", "18:00"),
                    ("19:00", "19:00"),
                    ("20:00", "20:00"),
                    ("21:00", "21:00"),
                    ("22:00", "22:00"),
                    ("23:00", "23:00"),
                ],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="days_of_week",
            field=models.ManyToManyField(to="tracker.dayofweek"),
        ),
    ]
