# Generated by Django 5.0.4 on 2024-04-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_dayofweek_remove_activity_days_of_week_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
